- type: gameMapPool
  id: StoriesDefaultMapPool
  maps:
  - StoriesAspid
  - StoriesAtlas
  - StoriesAvrite
  - StoriesBagel
  - StoriesBarratry
  - StoriesBox    # SP
  - StoriesCluster
  - StoriesCore
  - StoriesDelta
# - StoriesEuropa
  - StoriesFland  # SP
  - StoriesGemini
  - StoriesKettle # SP
  - StoriesMarathon
  - StoriesMeta
  - StoriesOmega
  - StoriesOrigin
  - StoriesPacked
  - StoriesReach
  - StoriesSaltern

# Corvax Maps
  - StoriesAvrite
  - StoriesDelta
  - StoriesGate
  - StoriesOutpost
  - StoriesSilly
  - StoriesSpectrum
