- type: gameMapPool
  id: StoriesDefaultMapPool
  maps:
  - StoriesAspid
  - StoriesBagel
  - StoriesBarratry
  - StoriesCluster
  - StoriesCore
  - StoriesOmega
  - StoriesPacked
  - StoriesMarathon
  - StoriesAtlas

# Corvax Maps
  - StoriesAvrite
  - StoriesDelta
#  - CorvaxGate
#  - CorvaxGelta
#  - CorvaxSpectrum

# Space Prison Maps
  - StoriesBox
  - StoriesFland
  - StoriesKettle

# New Maps
#  - StoriesEuropa
  - StoriesMeta
  - StoriesOrigin
  - StoriesSaltern
