- type: gameMapPool
  id: StoriesDefaultMapPool
  maps:
  - StoriesAspid    # Space Prison
  - StoriesAtlas
  - StoriesBagel
  - StoriesBox
  - StoriesCluster
  - StoriesCore
  - StoriesFland    # Space Prison
  - StoriesGemini
  - StoriesMarathon
  - StoriesMeta     # Space Prison
  - StoriesOmega
  - StoriesOrigin
  - StoriesSaltern
  - StoriesPacked
  - StoriesReach
