- type: gameMapPool
  id: StoriesDefaultMapPool
  maps:
  - StoriesAspid
  - StoriesBagel
  - StoriesBarratry
  - StoriesCluster
  - StoriesCore
  - StoriesOmega
  - StoriesPacked
  - StoriesAvrite
  - StoriesDelta
#  - CorvaxGate
#  - CorvaxGelta
#  - CorvaxSpectrum
  - StoriesBox
  - StoriesFland
  - StoriesKettle
  - StoriesMarathon
