- type: playTimeTracker
  id: JobHeadOfSpacePrison

- type: playTimeTracker
  id: JobSpacePrisonOfficer

- type: playTimeTracker
  id: JobSpacePrisonEngineer

- type: playTimeTracker
  id: JobSpacePrisonMedic

- type: playTimeTracker
  id: JobIAA

- type: playTimeTracker
  id: JobJediNt

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorResearcher

# CC Jobs start
- type: playTimeTracker
  id: JobOCC

- type: playTimeTracker
  id: JobDCC

- type: playTimeTracker
  id: JobOfficerCC

- type: playTimeTracker
  id: JobECC

- type: playTimeTracker
  id: JobMCC

- type: playTimeTracker
  id: JobSCC

- type: playTimeTracker
  id: JobHSCC
# CC Jobs end