- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 #20 hrs # Stories-RoleTime
  - !type:DepartmentTimeRequirement
    department: Civilian
    time: 18000 #5 hrs
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hop
  canBeAntag: true
  access:
  - Brig
  - Maintenance
  - Service
  - Detective

- type: startingGear
  id: DetectiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    outerClothing: ClothingOuterVestDetective
    back: ClothingBackpackFilledDetective
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite-MRP
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatFedoraBrown
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  innerClothingSkirt: ClothingUniformJumpskirtDetective
  satchel: ClothingBackpackSatchelFilledDetective
  duffelbag: ClothingBackpackDuffelFilledDetective
