- type: job
  id: MCC
  name: job-name-medic-cent-comm
  description: medic-cent-comm-desc
  playTimeTracker: JobMCC
  weight: 10
  startingGear: MCCGear
  icon: "JobIconMCC"
  supervisors: job-supervisors-chief-of-staff
  canBeAntag: false
  accessGroups:
    - AllAccess
  access:
    - CentralCommand
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]

- type: startingGear
  id: MCCGear
  equipment:
    head: ClothingHeadHatBeretCmo
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorWhite
    id: CentcomPDA
    eyes: ClothingEyesHudMedical
    belt: ClothingBeltMedicalFilled
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterCoatAMG
    pocket1: Hypospray
    pocket2: OmnizineChemistryBottle
