- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10h Stories-RoleTime

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15h Stories-RoleTime
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 36000 # 10h Stories-RoleTime

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 72000 # 10h Stories-RoleTime
  - !type:DepartmentTimeRequirement
    department: Command
    time: 36000 # 10h Stories-RoleTime
  # should be changed to nukie playtime when thats tracked (wyci)
