- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: roles-antag-space-ninja-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15h Stories-RoleTime
